# Generated by Django 3.0.6 on 2020-07-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Useraccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=30, null=True, verbose_name='firstname')),
                ('last_name', models.CharField(max_length=30, null=True, verbose_name='lastname')),
                ('gender', models.CharField(max_length=20, null=True, verbose_name='gender')),
                ('age', models.CharField(max_length=10, null=True, verbose_name='age')),
                ('country', models.CharField(max_length=30, null=True, verbose_name='country')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=5)),
                ('like_username', models.CharField(max_length=20)),
                ('like_email', models.EmailField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=60)),
                ('time', models.CharField(max_length=20)),
                ('post_text', models.CharField(max_length=100)),
                ('post_img', models.CharField(max_length=50)),
            ],
        ),
    ]
